#!/usr/bin/env bash
#Prints 'bad luck' for i == 4, 'good luck' for i == 8 and 'Best School' for rest
i="0"
while [ $i -lt 10 ]
do
	if ((i == 3))
	then
		echo "bad luck"
	elif ((i == 7))
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
